name: polysignal
region: nyc

services:
  - name: frontend
    github:
      repo: evansmakori/PolySignal-Polymarket-Analytics-Platform
      branch: main
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 80
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: VITE_API_BASE_URL
        value: "http://138.197.231.111"
        scope: BUILD_TIME
